language: python

before_install:
  - git clone https://github.com/GoogleCloudPlatform/gcloud-python-wheels
        gcloud-python-wheels
  - export WHEELHOUSE="$(pwd)/gcloud-python-wheels/wheelhouse/"

install:
  - scripts/custom_pip_install.sh tox

script:
  - tox -e py26
  - tox -e py27
  - tox -e lint
  - tox -e regression
  - scripts/merge.sh

after_success:
  - tox -e coveralls
